spring:
  application:
    name: ChatUnity
  datasource:
    url: jdbc:mysql://localhost:3306/aitoolbox
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  ai:
    dashscope:
      api-key: sk-2bad25356fc546fa85f792652b34af8e
      # 引入阿里千问
      chat:
        options:
          model: qwen-plus-2025-07-28
    # 引入deepseek
    deepseek:
      api-key: sk-72b6f63b5099437d94ca8b5cd370b8c8
      chat:
        options:
          model: deepseek-chat

    # 引入智谱AI
    zhipuai:
      api-key: 0e3fa20e31f94e388a6ed827834038f5.fn86ydXOj9teSq20
      chat:
        options:
          model: glm-4.5v

    # 引入ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:1b
      embedding:
        options:
          model: qwen3-embedding:latest


  # Redis设置
  data:
    redis:
      port: 6379
      database: 0
      username: root
      password:
      host: localhost
      timeout: 3600

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug

# 引入阿里万相自定义
alibaba:
  image:
    model:
      base_url: https://dashscope.aliyuncs.com/api/v1
      api_key: sk-2bad25356fc546fa85f792652b34af8e
      model_name: wan2.5-t2i-preview