spring:
  application:
    name: ChatReact
  datasource:
    url: jdbc:mysql://localhost:3306/chatmemory
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678

  ai:
    dashscope:
      # 需要去阿里百炼申请api
      api-key:
      chat:
        options:
          # 这个值0~1，值越大代表生成的结果随机性越强。如果是一个聊天，这个值可以大一点。如果是一些严谨的规划，则这个值可以设置小一些
          temperature: 0.7
          model: qwen-plus-2025-09-11
      embedding:
        options:
          model: text-embedding-v4
    mcp:
      client:
        type: sync
        sse:
          connections:
            # 需要去魔塔找搜狗搜索mcp
            server1:
              url:
              sse-endpoint:

  data:
    redis:
      host: localhost
      port: 6379
      username: root
      password:
      database: 0

logging:
  level:
    io.modelcontextprotocol:
      client: DEBUG
      spec: DEBUG
    com.alibaba.cloud.ai: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.web: DEBUG