spring:
  profiles:
    active: dev
  application:
    name: AIToolsBox
  datasource:
    url: jdbc:mysql://localhost:3306/aitoolbox
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  ai:
    dashscope:
      api-key: ${YOUR_API_KEY}
      # 引入阿里千问
      chat:
        options:
          model: qwen-plus-2025-07-28
    # 引入deepseek
    deepseek:
      api-key: ${YOUR_API_KEY}
      chat:
        options:
          model: deepseek-chat

    # 引入智谱AI
    zhipuai:
      api-key: ${YOUR_API_KEY}
      chat:
        options:
          model: glm-4.5v

    # 引入ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:1b
      embedding:
        options:
          model: qwen3-embedding:latest
    # 使用mcp
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json


  # Redis设置
  data:
    redis:
      port: 6379
      database: 0
      # 如果 Redis 没有启用认证，则不需要 password
      # 如果 Redis 使用密码认证（不需要用户名），设置密码：
      # password: your_redis_password
      host: localhost
      timeout: 3600

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug

# 引入阿里巴巴通义千问/万相自定义
alibaba:
  base_url: https://dashscope.aliyuncs.com/api/v1
  api_key: ${YOUR_API_KEY}
  image:
    model_name: wan2.5-t2i-preview
  video:
    model_name: wan2.5-t2v-preview

search-api:
  api-key: ${YOUR_API_KEY}

# 设置超时时间
chat:
  memory:
    redis:
      ttl-minutes: 60

# COS
cos:
  client:
    bucket:
    host:
    secret-id:
    secret-key:
    region: