spring:
  application:
    name: ChatReact
  ai:
    dashscope:
      api-key: sk-594fe081db954603b2b7bd9a29691003
      chat:
        options:
          model: qwen-plus-2025-09-11
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:270m
        enabled: false

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug