spring:
  application:
    name: ChatReact
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678

  ai:
    # 引入阿里千问
    dashscope:
      api-key: sk-2bad25356fc546fa85f792652b34af8e
      chat:
        options:
          model: qwen3-vl-plus
    #      embedding:
    #        options:
    #          model: text-embedding-v4
    # 引入deepseek
    deepseek:
      api-key: sk-72b6f63b5099437d94ca8b5cd370b8c8
      chat:
        options:
          model: deepseek-chat

    # 引入智谱AI
    zhipuai:
      api-key: 0e3fa20e31f94e388a6ed827834038f5.fn86ydXOj9teSq20
      chat:
        options:
          model: glm-4.5v

    # 引入ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:latest
      embedding:
        options:
          model: qwen3-embedding:latest

    # mcp配置
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC
        sse:
          connections:
            server1:
              url: http://localhost:8080
        stdio:
          connections:
            server1:
              command: /path/to/server
              args:
                - --port=8080
              env:
                API_KEY: your-api-key


  # Redis设置
  data:
    redis:
      port: 6379
      database: 0
      username: root
      password:
      host: localhost
      timeout: 5000

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug